### PR TITLE
Propper screen clearing

### PR DESCRIPTION
**Pull request by r00terAF18**
Hello, i replaced the original screen clearing function with one that would always properly worked since it had a few issues on my machine(parrot os kde)
thanks

### CODE REVIEW

**Comment by CRO-THEHACKER** [comment]
PR denied, no use for windows and linux. Repo is linux-only..

**Comment by r00terAF18** [comment]
Thank you for your feedback and taking your time for reacting to my merge request, I understand and thus will try to be more useful next time

**Comment by CRO-THEHACKER** [comment]
No no, don't worry. Just saying lol it's been a long day and I just was looking at github. Sorry if that seemed rude in any way. 

Feel free to join the discord, [discord link](https://fsocietyproject.ml/discord)

**Comment by r00terAF18** [comment]
No that wasn't rude at all, genuine feedback to my bad merging request, thats all.

**Comment by CRO-THEHACKER** [comment]
Sounds good. Thanks anyway! We appreciate it.

**Pull request closed without merging**
